resolver:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/21.yaml

packages:
- .

extra-deps:
- hascalam-0.1.1.1@sha256:73fbd71e8b97a7acb281d77548a4fe3cd99200da66d07fb211401a9d74cf6f14,1664

system-ghc: false
